import "./globals.css";
import Footer from "./components/footer/Footer";
import Header from "./components/Header/Header";
import { Background } from "./components/common/LightRays";
export const metadata = {
  title: "M_SaadD_ZeB",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Background />
        <Header />
        {children}

        <Footer />
      </body>
    </html>
  );
}
